# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lenet/lenet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet || ORIG_REF_NAME==lenet}]

# IP: bd/lenet/ip/lenet_processing_system7_0_0/lenet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_processing_system7_0_0 || ORIG_REF_NAME==lenet_processing_system7_0_0}]

# IP: bd/lenet/ip/lenet_c1_0_0/lenet_c1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_c1_0_0 || ORIG_REF_NAME==lenet_c1_0_0}]

# IP: bd/lenet/ip/lenet_ps7_0_axi_periph_0/lenet_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_ps7_0_axi_periph_0 || ORIG_REF_NAME==lenet_ps7_0_axi_periph_0}]

# IP: bd/lenet/ip/lenet_rst_ps7_0_100M_0/lenet_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_rst_ps7_0_100M_0 || ORIG_REF_NAME==lenet_rst_ps7_0_100M_0}]

# IP: bd/lenet/ip/lenet_axi_dma_0_0/lenet_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_axi_dma_0_0 || ORIG_REF_NAME==lenet_axi_dma_0_0}]

# IP: bd/lenet/ip/lenet_axi_smc_0/lenet_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_axi_smc_0 || ORIG_REF_NAME==lenet_axi_smc_0}]

# IP: bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_axi_timer_0_0 || ORIG_REF_NAME==lenet_axi_timer_0_0}]

# IP: bd/lenet/ip/lenet_xbar_0/lenet_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_xbar_0 || ORIG_REF_NAME==lenet_xbar_0}]

# IP: bd/lenet/ip/lenet_auto_pc_0/lenet_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lenet_auto_pc_0 || ORIG_REF_NAME==lenet_auto_pc_0}]

# XDC: bd/lenet/lenet_ooc.xdc
