# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/project/lenet-5/lenet-5/lenet-5.cache/wt [current_project]
set_property parent.project_path F:/project/lenet-5/lenet-5/lenet-5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths f:/hls_lenet/hls_lenet/solution1 [current_project]
set_property ip_output_repo f:/project/lenet-5/lenet-5/lenet-5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib F:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/hdl/lenet_wrapper.vhd
add_files F:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/lenet.bd
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_processing_system7_0_0/lenet_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_c1_0_0/constraints/c1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_rst_ps7_0_100M_0/lenet_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_rst_ps7_0_100M_0/lenet_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_rst_ps7_0_100M_0/lenet_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_dma_0_0/lenet_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_dma_0_0/lenet_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_dma_0_0/lenet_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_10/bd_4e18_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_16/bd_4e18_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_20/bd_4e18_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_21/bd_4e18_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_22/bd_4e18_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_23/bd_4e18_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_24/bd_4e18_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_25/bd_4e18_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_17/bd_4e18_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_18/bd_4e18_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_19/bd_4e18_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_11/bd_4e18_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_12/bd_4e18_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_2/bd_4e18_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_3/bd_4e18_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_4/bd_4e18_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_5/bd_4e18_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_6/bd_4e18_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_1/bd_4e18_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/bd_0/ip/ip_1/bd_4e18_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_xbar_0/lenet_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_auto_pc_0/lenet_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/lenet_ooc.xdc]
set_property is_locked true [get_files F:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/lenet.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lenet_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef lenet_wrapper.dcp

catch { report_utilization -file lenet_wrapper_utilization_synth.rpt -pb lenet_wrapper_utilization_synth.pb }
