// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xc1.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XC1_CfgInitialize(XC1 *InstancePtr, XC1_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->Kernel_bus_BaseAddress = ConfigPtr->Kernel_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XC1_Start(XC1 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XC1_IsDone(XC1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XC1_IsIdle(XC1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XC1_IsReady(XC1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XC1_EnableAutoRestart(XC1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XC1_DisableAutoRestart(XC1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_AP_CTRL, 0);
}

u32 XC1_Get_filter_w_BaseAddress(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_BASE);
}

u32 XC1_Get_filter_w_HighAddress(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH);
}

u32 XC1_Get_filter_w_TotalBytes(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + 1);
}

u32 XC1_Get_filter_w_BitWidth(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_KERNEL_BUS_WIDTH_FILTER_W;
}

u32 XC1_Get_filter_w_Depth(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_KERNEL_BUS_DEPTH_FILTER_W;
}

u32 XC1_Write_filter_w_Words(XC1 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XC1_Read_filter_w_Words(XC1 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + (offset + i)*4);
    }
    return length;
}

u32 XC1_Write_filter_w_Bytes(XC1 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XC1_Read_filter_w_Bytes(XC1 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XC1_KERNEL_BUS_ADDR_FILTER_W_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_W_BASE + offset + i);
    }
    return length;
}

u32 XC1_Get_filter_b_BaseAddress(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_BASE);
}

u32 XC1_Get_filter_b_HighAddress(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH);
}

u32 XC1_Get_filter_b_TotalBytes(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + 1);
}

u32 XC1_Get_filter_b_BitWidth(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_KERNEL_BUS_WIDTH_FILTER_B;
}

u32 XC1_Get_filter_b_Depth(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_KERNEL_BUS_DEPTH_FILTER_B;
}

u32 XC1_Write_filter_b_Words(XC1 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XC1_Read_filter_b_Words(XC1 *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + (offset + i)*4);
    }
    return length;
}

u32 XC1_Write_filter_b_Bytes(XC1 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XC1_Read_filter_b_Bytes(XC1 *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XC1_KERNEL_BUS_ADDR_FILTER_B_HIGH - XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Kernel_bus_BaseAddress + XC1_KERNEL_BUS_ADDR_FILTER_B_BASE + offset + i);
    }
    return length;
}

void XC1_InterruptGlobalEnable(XC1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_GIE, 1);
}

void XC1_InterruptGlobalDisable(XC1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_GIE, 0);
}

void XC1_InterruptEnable(XC1 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_IER);
    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XC1_InterruptDisable(XC1 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_IER);
    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XC1_InterruptClear(XC1 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XC1_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XC1_InterruptGetEnabled(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_IER);
}

u32 XC1_InterruptGetStatus(XC1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XC1_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XC1_CRTL_BUS_ADDR_ISR);
}

