// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xc1.h"

extern XC1_Config XC1_ConfigTable[];

XC1_Config *XC1_LookupConfig(u16 DeviceId) {
	XC1_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XC1_NUM_INSTANCES; Index++) {
		if (XC1_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XC1_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XC1_Initialize(XC1 *InstancePtr, u16 DeviceId) {
	XC1_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XC1_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XC1_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

