// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XC1_H
#define XC1_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xc1_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
    u32 Kernel_bus_BaseAddress;
} XC1_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 Kernel_bus_BaseAddress;
    u32 IsReady;
} XC1;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XC1_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XC1_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XC1_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XC1_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XC1_Initialize(XC1 *InstancePtr, u16 DeviceId);
XC1_Config* XC1_LookupConfig(u16 DeviceId);
int XC1_CfgInitialize(XC1 *InstancePtr, XC1_Config *ConfigPtr);
#else
int XC1_Initialize(XC1 *InstancePtr, const char* InstanceName);
int XC1_Release(XC1 *InstancePtr);
#endif

void XC1_Start(XC1 *InstancePtr);
u32 XC1_IsDone(XC1 *InstancePtr);
u32 XC1_IsIdle(XC1 *InstancePtr);
u32 XC1_IsReady(XC1 *InstancePtr);
void XC1_EnableAutoRestart(XC1 *InstancePtr);
void XC1_DisableAutoRestart(XC1 *InstancePtr);

u32 XC1_Get_filter_w_BaseAddress(XC1 *InstancePtr);
u32 XC1_Get_filter_w_HighAddress(XC1 *InstancePtr);
u32 XC1_Get_filter_w_TotalBytes(XC1 *InstancePtr);
u32 XC1_Get_filter_w_BitWidth(XC1 *InstancePtr);
u32 XC1_Get_filter_w_Depth(XC1 *InstancePtr);
u32 XC1_Write_filter_w_Words(XC1 *InstancePtr, int offset, int *data, int length);
u32 XC1_Read_filter_w_Words(XC1 *InstancePtr, int offset, int *data, int length);
u32 XC1_Write_filter_w_Bytes(XC1 *InstancePtr, int offset, char *data, int length);
u32 XC1_Read_filter_w_Bytes(XC1 *InstancePtr, int offset, char *data, int length);
u32 XC1_Get_filter_b_BaseAddress(XC1 *InstancePtr);
u32 XC1_Get_filter_b_HighAddress(XC1 *InstancePtr);
u32 XC1_Get_filter_b_TotalBytes(XC1 *InstancePtr);
u32 XC1_Get_filter_b_BitWidth(XC1 *InstancePtr);
u32 XC1_Get_filter_b_Depth(XC1 *InstancePtr);
u32 XC1_Write_filter_b_Words(XC1 *InstancePtr, int offset, int *data, int length);
u32 XC1_Read_filter_b_Words(XC1 *InstancePtr, int offset, int *data, int length);
u32 XC1_Write_filter_b_Bytes(XC1 *InstancePtr, int offset, char *data, int length);
u32 XC1_Read_filter_b_Bytes(XC1 *InstancePtr, int offset, char *data, int length);

void XC1_InterruptGlobalEnable(XC1 *InstancePtr);
void XC1_InterruptGlobalDisable(XC1 *InstancePtr);
void XC1_InterruptEnable(XC1 *InstancePtr, u32 Mask);
void XC1_InterruptDisable(XC1 *InstancePtr, u32 Mask);
void XC1_InterruptClear(XC1 *InstancePtr, u32 Mask);
u32 XC1_InterruptGetEnabled(XC1 *InstancePtr);
u32 XC1_InterruptGetStatus(XC1 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
