# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_xbar_0/lenet_xbar_0.xci
# IP: The module: 'lenet_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_xbar_0/lenet_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_xbar_0/lenet_xbar_0.xci
# IP: The module: 'lenet_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_xbar_0/lenet_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
