# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xci
# IP: The module: 'lenet_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xci
# IP: The module: 'lenet_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/project/lenet-5/lenet-5/lenet-5.srcs/sources_1/bd/lenet/ip/lenet_axi_timer_0_0/lenet_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenet_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
